SiKeju/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^tambahJadwal/', tambahJadwal, name='tambahJadwal'),
    url(r'^put/', put, name='put')
]

sistem_ceria/urls.py
from django.conf.urls import include, url
from django.views.generic.base import RedirectView
from django.contrib import admin
import SiKeju.urls as SiKeju


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^SiKeju/', include(SiKeju, namespace='SiKeju')),
    url(r'^$', RedirectView.as_view(url = "/SiKeju/", permanent = "true"), name = 'index')
]

SiKeju/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
	no_slot = models.IntegerField(primary_key=True, unique=True)
	hari = models.CharField(max_length=100)
	jam = models.IntegerField()
	
class Ruang(models.Model):
	nama_ruang = models.CharField(max_length=100, primary_key = True, unique=True)
	kapasitas = models.IntegerField(max_length = 10)

class Reserve(models.Model):
	jadwal = models.ForeignKey(Jadwal, on_delete=models.CASCADE)
	ruang = models.ForeignKey(Ruang, on_delete=models.CASCADE)
	matkul = models.CharField(max_length=100)

	class Meta:
		unique_together = (("jadwal", "ruang"),)

SiKeju/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import SuspiciousOperation
from django.db import IntegrityError
from .model_helper import *
import json

# Create your views here.
response = {}

def index(request):
    reserve = getAllReserve()
    response['reserve'] = reserve
    html = 'SiKeju/awal.html'
    return render(request, html, response)

@csrf_exempt
@require_http_methods(['GET','POST'])
def tambahJadwal(request):
    print("A")
    print(request.method)
    if request.method == 'GET' :
        return render(request,'SiKeju/indexPlus.html',response)
    else :
        print("c")

@csrf_exempt
@require_http_methods(['GET','POST'])
def put(request):
    try:
        data = json.loads(request.body.decode('utf-8'))
        hariCari = data['hari']
        jamCari = int(data['jam'])
        idRuang = data['ruang']
        idHari = 0
        idJam = 0
        ida = 0
        counter = 0
        print (data)
        done = False
        
        while(counter != 15) :
            counter += 1
            if hariCari == 'Senin':
                idHari = 0
            elif hariCari == 'Selasa':
                idHari = 1
            elif hariCari == 'Rabu': 
                idHari = 2
            elif hariCari == 'Kamis':
                idHari = 3
            elif hariCari == 'Jumat':
                idHari = 4
                
            if jamCari == 9:
                idJam = 1
            elif jamCari == 13:
                idJam = 2
            elif jamCari == 16:
                idJam = 3
            try:
                ida = (3*idHari) +  idJam;
                # print (ida)
                if int(data['jumlah_kelas']) <= (10 - countReserve(ida)):
                    j = 0
                    cek = 0
                    while j < int(data['jumlah_kelas']):
                        cek += 1
                        ruang = getRuang(idRuang)
                        print (ruang)
                        if int(data['kapasitas']) < ruang["kapasitas"] and not getReserve(ida, idRuang):
                            putReserve(ida, idRuang, data['mata_kuliah'])
                            j = j+1
                            if j == int(data['jumlah_kelas']) :
                                done = True
                        else :
                            if idRuang == "R01":
                                idRuang = "R02"
                            elif idRuang == "R02":
                                idRuang = "R03"
                            elif idRuang == "R03":
                                idRuang = "R04"
                            elif idRuang == "R04":
                                idRuang = "R05"
                            elif idRuang == "R05":
                                idRuang = "R06"
                            elif idRuang == "R06":
                                idRuang = "R07"
                            elif idRuang == "R07":
                                idRuang = "R08"
                            elif idRuang == "R08":
                                idRuang = "R09"
                            elif idRuang == "R09":
                                idRuang = "R10"
                            elif idRuang == "R10":
                                idRuang = "R01"
                        if cek == 10:
                            break
                else:
                    if jamCari == 9:
                        jamCari = 13
                    elif jamCari == 13:
                        jamCari = 16
                    else :
                        if hariCari == 'Senin':
                            hariCari = 'Selasa'
                        elif hariCari == 'Selasa':
                            hariCari = 'Rabu'
                        elif hariCari == 'Rabu':
                            hariCari = 'Kamis'
                        elif hariCari == 'Kamis':
                            hariCari = 'Jumat'
                        else :
                            hariCari = 'Senin'
                        jamCari = 9
            except Exception as e:
                print (e)
                
            if done :
                break

            if counter == 15:
                return JsonResponse({'status':'invalid'})
        return JsonResponse({'status':'valid'})
    except IntegrityError:
        return JsonResponse({'status':'invalid'})
    except:
        return HttpResponse("<h1>Bad Request</h1>",status=400)

SiKeju/templates/SiKeju/awal.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/awal.css' %}" /> 
  <link rel="stylesheet" href="https://v40.pingendo.com/assets/4.0.0/default/theme.css" type="text/css"> </head>
<img src="{% static 'keju.png' %}" style="width: 436px;height: 436px;margin-left: auto;margin-right: auto;display: block;">
<body style="background-color: aliceblue">
  <div class="py-5">
    <div class="container">
      <h4 class="" style="font-weight: bold">Senin</h4>
      <div class="row">
        <div class="col-md-4"  style="border: 1px solid" >
          <p id="Senin1" style="font-weight: bold;font-size: 20px">09.00 - 11.30</p>
		  {% for i in reserve %}
		  {% if i.hari == 'Senin' %}
		  {% if i.jam == 9 %}
		  <tr> {{i.matkul}} </tr>
		  <br>
		  <tr> {{i.ruang}} </tr>
		  <br>
		  <br>
		  {% endif %}
		  {% endif %}
		  {% endfor %}
        </div>
        <div class="col-md-4"  style="border: 1px solid" >
          <p id="Senin2" style="font-weight: bold;font-size: 20px">13.00 - 15.30</p>
		  {% for i in reserve %}
		  {% if i.hari == 'Senin' %}
		  {% if i.jam == 13 %}
		  <tr> {{i.matkul}} </tr>
		  <br>
		  <tr> {{i.ruang}} </tr>
		  <br>
		  <br>
		  {% endif %}
		  {% endif %}
		  {% endfor %}
        </div>
        <div class="col-md-4"  style="border: 1px solid" >
          <p id="Senin3" style="font-weight: bold;font-size: 20px">16.00 - 18.30</p>
		  {% for i in reserve %}
		  {% if i.hari == 'Senin' %}
		  {% if i.jam == 16 %}
		  <tr> {{i.matkul}} </tr>
		  <br>
		  <tr> {{i.ruang}} </tr>
		  <br>
		  <br>
		  {% endif %}
		  {% endif %}
		  {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <h4 class="" style="font-weight: bold">Selasa</h4>
      <div class="row">
        <div class="col-md-4"  style="border: 1px solid" >
          <p id="Selasa1" style="font-weight: bold;font-size: 20px">09.00 - 11.30</p>
		  {% for i in reserve %}
		  {% if i.hari == 'Selasa' %}
		  {% if i.jam == 9 %}
		  <tr> {{i.matkul}} </tr>
		  <br>
		  <tr> {{i.ruang}} </tr>
		  <br>
		  <br>
		  {% endif %}
		  {% endif %}
		  {% endfor %}
        </div>
        <div class="col-md-4"  style="border: 1px solid" >
          <p id="Selasa2" style="font-weight: bold;font-size: 20px">13.00 - 15.30</p>
		  {% for i in reserve %}
		  {% if i.hari == 'Selasa' %}
		  {% if i.jam == 13 %}
		  <tr> {{i.matkul}} </tr>
		  <br>
		  <tr> {{i.ruang}} </tr>
		  <br>
		  <br>
		  {% endif %}
		  {% endif %}
		  {% endfor %}
        </div>
        <div class="col-md-4"  style="border: 1px solid" >
          <p id="Selasa3" style="font-weight: bold;font-size: 20px">16.00 - 18.30</p>
		  {% for i in reserve %}
		  {% if i.hari == 'Selasa' %}
		  {% if i.jam == 16 %}
		  <tr> {{i.matkul}} </tr>
		  <br>
		  <tr> {{i.ruang}} </tr>
		  <br>
		  <br>
		  {% endif %}
		  {% endif %}
		  {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <h4 class="" style="font-weight: bold">Rabu</h4>
      <div class="row">
        <div class="col-md-4"  style="border: 1px solid" >
          <p id="Rabu1" style="font-weight: bold;font-size: 20px">09.00 - 11.30</p>
		  {% for i in reserve %}
		  {% if i.hari == 'Rabu' %}
		  {% if i.jam == 9 %}
		  <tr> {{i.matkul}} </tr>
		  <br>
		  <tr> {{i.ruang}} </tr>
		  <br>
		  <br>
		  {% endif %}
		  {% endif %}
		  {% endfor %}
        </div>
        <div class="col-md-4"  style="border: 1px solid" >
          <p id="Rabu2" style="font-weight: bold;font-size: 20px">13.00 - 15.30</p>
		  {% for i in reserve %}
		  {% if i.hari == 'Rabu' %}
		  {% if i.jam == 13 %}
		  <tr> {{i.matkul}} </tr>
		  <br>
		  <tr> {{i.ruang}} </tr>
		  <br>
		  <br>
		  {% endif %}
		  {% endif %}
		  {% endfor %}
        </div>
        <div class="col-md-4"  style="border: 1px solid" >
          <p id="Rabu3" style="font-weight: bold;font-size: 20px">16.00 - 18.30</p>
		  {% for i in reserve %}
		  {% if i.hari == 'Rabu' %}
		  {% if i.jam == 16 %}
		  <tr> {{i.matkul}} </tr>
		  <br>
		  <tr> {{i.ruang}} </tr>
		  <br>
		  <br>
		  {% endif %}
		  {% endif %}
		  {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <h4 class="" style="font-weight: bold">Kamis</h4>
      <div class="row">
        <div class="col-md-4"  style="border: 1px solid" >
          <p id="Kamis1" style="font-weight: bold;font-size: 20px">09.00 - 11.30</p>
		  {% for i in reserve %}
		  {% if i.hari == 'Kamis' %}
		  {% if i.jam == 9 %}
		  <tr> {{i.matkul}} </tr>
		  <br>
		  <tr> {{i.ruang}} </tr>
		  <br>
		  <br>
		  {% endif %}
		  {% endif %}
		  {% endfor %}
        </div>
        <div class="col-md-4"  style="border: 1px solid" >
          <p id="Kamis2" style="font-weight: bold;font-size: 20px">13.00 - 15.30</p>
		  {% for i in reserve %}
		  {% if i.hari == 'Kamis' %}
		  {% if i.jam == 13 %}
		  <tr> {{i.matkul}} </tr>
		  <br>
		  <tr> {{i.ruang}} </tr>
		  <br>
		  <br>
		  {% endif %}
		  {% endif %}
		  {% endfor %}
        </div>
        <div class="col-md-4"  style="border: 1px solid" >
          <p id="Kamis3" style="font-weight: bold;font-size: 20px">16.00 - 18.30</p>
		  {% for i in reserve %}
		  {% if i.hari == 'Kamis' %}
		  {% if i.jam == 16 %}
		  <tr> {{i.matkul}} </tr>
		  <br>
		  <tr> {{i.ruang}} </tr>
		  <br>
		  <br>
		  {% endif %}
		  {% endif %}
		  {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <h4 class="" style="font-weight: bold">Jumat</h4>
      <div class="row">
        <div class="col-md-4"  style="border: 1px solid" >
          <p id="Jumat1" style="font-weight: bold;font-size: 20px">09.00 - 11.30</p>
		  {% for i in reserve %}
		  {% if i.hari == 'Jumat' %}
		  {% if i.jam == 9 %}
		  <tr> {{i.matkul}} </tr>
		  <br>
		  <tr> {{i.ruang}} </tr>
		  <br>
		  <br>
		  {% endif %}
		  {% endif %}
		  {% endfor %}
        </div>
        <div class="col-md-4"  style="border: 1px solid" >
          <p id="Jumat2" style="font-weight: bold;font-size: 20px">13.00 - 15.30</p>
		  {% for i in reserve %}
		  {% if i.hari == 'Jumat' %}
		  {% if i.jam == 13 %}
		  <tr> {{i.matkul}} </tr>
		  <br>
		  <tr> {{i.ruang}} </tr>
		  <br>
		  <br>
		  {% endif %}
		  {% endif %}
		  {% endfor %}
        </div>
        <div class="col-md-4"  style="border: 1px solid" >
          <p id="Jumat3" style="font-weight: bold;font-size: 20px">16.00 - 18.30</p>
		  {% for i in reserve %}
		  {% if i.hari == 'Jumat' %}
		  {% if i.jam == 16 %}
		  <tr> {{i.matkul}} </tr>
		  <br>
		  <tr> {{i.ruang}} </tr>
		  <br>
		  <br>
		  {% endif %}
		  {% endif %}
		  {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <br>
  <br>
  <center>
  <a href="{% url 'SiKeju:tambahJadwal' %}" class="btn info" style="color:RoyalBlue">Tambah Jadwal</a>
  </center>


</body>

</html>

SiKeju/templates/SiKeju/content.html
{% load static %}
<div id="app" v-cloak>
    <div v-if="alert_success" class="alert alert-success">
        <strong>Pendaftaran berhasil!</strong>
        Anda akan redirect ke halaman jadwal dalam 3 detik.
    </div>
    <div v-if="alert_danger" class="alert alert-danger">
        <strong>Pendaftaran gagal!</strong> Mata Kuliah sudah terdaftar atau jadwal bentrok
    </div>

    <img src="{% static 'keju.png' %}" style="width: 436px;height: 436px;margin-left: auto;margin-right: auto;display: block;">
    <center>
    <div class="mt-5">
        <form @submit="submitForm">
            <div class="form-group row">
                <label for="mata_kuliah" class="col-sm-4 col-form-label">Nama Mata Kuliah</label>
                <div class="col-sm-8"> 
                    <input v-bind:class="['form-control', mata_kuliah.value==''?'':mata_kuliah.valid?'is-valid':'is-invalid']" v-model="mata_kuliah.value" type="text" id="mata_kuliah" size ="35" placeholder="Nama Mata Kuliah" required>
                </div>
            </div>
            <br>
			<div class="form-group row">
                <label for="hari" class="col-sm-4 col-form-label">Hari</label>
                <div class="col-sm-8">
                    <input v-bind:class="['form-control', hari.value==''?'':hari.valid?'is-valid':'is-invalid']" v-model="hari.value" type="text" id="hari" size ="35" placeholder="Senin/Selasa/Rabu/Kamis/Jumat (Pilih salah satu)" required>
                </div>
            </div>
            <br>
			<div class="form-group row">
                <label for="jam" class="col-sm-4 col-form-label">Jam</label>
                <div class="col-sm-8">
                    <input v-bind:class="['form-control', jam.value==''?'':jam.valid?'is-valid':'is-invalid']" v-model="jam.value" type="text" id="jam" size ="35" placeholder="9/13/16 (Pilih salah satu)" required>
                </div>
            </div>
            <br>
			<div class="form-group row">
                <label for="ruang" class="col-sm-4 col-form-label">Ruang</label>
                <div class="col-sm-8">
                    <input v-bind:class="['form-control', ruang.value==''?'':ruang.valid?'is-valid':'is-invalid']" v-model="ruang.value" type="text" id="ruang" size ="35" placeholder="R01-R10" required>
                </div>
            </div>
            <br>
			<div class="form-group row">
                <label for="kapasitas" class="col-sm-4 col-form-label">Jumlah Mahasiswa</label>
                <div class="col-sm-8">
                    <input v-bind:class="['form-control', kapasitas.value==''?'':kapasitas.valid?'is-valid':'is-invalid']" v-model="kapasitas.value" type="text" id="kapasitas" size ="35" placeholder="Jumlah Mahasiswa" required>
                </div>
            </div>
            <br>
			<div class="form-group row">
                <label for="jumlah_kelas" class="col-sm-4 col-form-label">Jumlah Kelas</label>
                <div class="col-sm-8">
                    <input v-bind:class="['form-control', jumlah_kelas.value==''?'':jumlah_kelas.valid?'is-valid':'is-invalid']" v-model="jumlah_kelas.value" type="text" id="jumlah_kelas" size ="35" placeholder="Jumlah Kelas yang dibutuhkan" required>
                </div>
            </div>
            <br>
            <button type="submit" class="btn btn-success mb-2">Submit</button>
            <button type="button" @click="cancelRegister" class="btn btn-danger mb-2">Cancel</button>
        </form>
    </div>
    </center>
</div>

SiKeju/templates/SiKeju/indexPlus.html
{% load static %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" /> 
{% endblock %}
{% block content %}
{% include "SiKeju/content.html" %}
{% endblock %}
{% block script %}
<script src="https://cdn.jsdelivr.net/npm/vue@2.5.13/dist/vue.min.js"></script>	
<script src="https://cdn.jsdelivr.net/npm/vue-resource@1.3.5"></script>
<script src="{% static 'js/index.js' %}"></script>
{% endblock %}